#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Start applications from ~/.local/bin/autostart
feh --bg-scale ~/Pictures/wallpapers/Arch-2.jpg
picom &
dunst &
$HOME/.config/polybar/launch.sh &

# bspwm settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 &
# bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 &

bspc config window_gap 20
bspc config border_width 2

bspc config normal_border_color "#89b4fa"
bspc config focused_border_color "#1a75ff"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Zathura state=tiled
